CC=gcc
AR=ar
MAIN = main.c
OBJECTS_MAIN=main.o
BASIC = basic.o
LOOP = advancedClassificatioloop.o
RECURSIVE = advancedClassificationRecursive.o
NUMCLASS = NumClass.h
FLAGS= -Wall -g

all: loops recursives recursived loopd mains maindloop maindrec

loops: libclassloops.a 
libclassloops.a: $(BASIC)	$(LOOP)
	$(AR) -rcs libclassloops.a $(BASIC) $(LOOP)

recursives: libclassrec.a
libclassrec.a: $(BASIC) $(RECURSIVE)
	$(AR) -rcs libclassrec.a $(BASIC) $(RECURSIVE)

recursived: libclassrec.so 
libclassrec.so: $(BASIC) $(RECURSIVE)
	$(CC) -shared -o libclassrec.so $(BASIC) $(RECURSIVE)

loopd: libclassloops.so
libclassloops.so: $(BASIC) $(LOOP)
	$(CC) -shared -o libclassloops.so $(BASIC) $(LOOP)


mains: $(MAIN) libclassrec.a
	$(CC) $(FLAGS) -o mains $(MAIN) libclassrec.a

maindloop: $(MAIN)
	$(CC) $(FLAGS) -o maindloop $(MAIN) ./libclassloops.so

maindrec: $(MAIN)
	$(CC) $(FLAGS) -o maindrec $(MAIN) ./libclassrec.so


main.o: $(MAIN) $(NUMCLASS)
	$(CC) $(FLAGS) -c main.c

basicClassification.o: basicClassification.c $(NUMCLASS)
	$(CC) $(FLAGS) -fPIC -c basicClassification.c

advancedClassificationLoop.o: advancedClassificationLoop.c $(NUMCLASS)
	$(CC) $(FLAGS) -fPIC -c advancedClassificationLoop.c

advancedClassificationRecursion.o: advancedClassificationRecursion.c $(NUMCLASS)
	$(CC) $(FLAGS) -fPIC -c advancedClassificationRecursion.c


# .PHONY: clean all

clean:
	rm -f *.o *.a *.so mains maindrec maindloop